<?php

namespace App\Support;

/**
 * Azerbaijani titles for the XİF MN (HS) 2-digit chapters. Chapter titles are
 * NOT present in catalog.name (which starts at the 4-digit heading), so this is
 * the reference list used to name the rubricator's top level. Chapter 77 is
 * reserved in the HS and has no title.
 */
final class HsChapters
{
    /** @var array<string, string> */
    public const AZ = [
        '01' => 'Canlı heyvanlar',
        '02' => 'Ət və yeyilən ət subməhsulları',
        '03' => 'Balıqlar, xərçəngkimilər və molyusklar',
        '04' => 'Süd məhsulları; yumurta; təbii bal',
        '05' => 'Heyvan mənşəli digər məhsullar',
        '06' => 'Canlı ağaclar və bitkilər; kəsilmiş güllər',
        '07' => 'Tərəvəzlər və bəzi yeməli kök və kökümsovlar',
        '08' => 'Yeməli meyvələr və qoz-fındıq',
        '09' => 'Qəhvə, çay, mate və ədviyyatlar',
        '10' => 'Dənli bitkilər (taxıl)',
        '11' => 'Un-yarma sənayesi məhsulları; nişasta',
        '12' => 'Yağlı toxumlar və meyvələr; müxtəlif toxumlar',
        '13' => 'Şellak; kitrələr, qatranlar və bitki şirələri',
        '14' => 'Toxuculuq üçün bitki materialları',
        '15' => 'Heyvan və ya bitki mənşəli yağlar',
        '16' => 'Ət və balıq məhsullarından hazır məhsullar',
        '17' => 'Şəkər və şəkərdən qənnadı məmulatları',
        '18' => 'Kakao və ondan hazırlanan məhsullar',
        '19' => 'Dənli bitki və un məhsulları; unlu qənnadı',
        '20' => 'Tərəvəz və meyvə emalı məhsulları',
        '21' => 'Müxtəlif qida məhsulları',
        '22' => 'İçkilər, spirtli mayelər və sirkə',
        '23' => 'Qida sənayesi qalıqları; hazır heyvan yemi',
        '24' => 'Tütün və tütün əvəzediciləri',
        '25' => 'Duz; kükürd; torpaq və daş; gips, əhəng, sement',
        '26' => 'Filizlər, şlaklar və kül',
        '27' => 'Mineral yanacaq, neft və emal məhsulları',
        '28' => 'Qeyri-üzvi kimya məhsulları',
        '29' => 'Üzvi kimyəvi birləşmələr',
        '30' => 'Farmasevtik məhsullar',
        '31' => 'Gübrələr',
        '32' => 'Aşılayıcı və boyayıcı ekstraktlar; boyalar, laklar',
        '33' => 'Efir yağları; ətriyyat və kosmetika vasitələri',
        '34' => 'Sabun, səthi-aktiv maddələr, yuyucu vasitələr',
        '35' => 'Zülali maddələr; nişasta məhsulları; yapışqanlar',
        '36' => 'Partlayıcı maddələr; pirotexnika; kibrit',
        '37' => 'Foto və kino üçün mallar',
        '38' => 'Müxtəlif kimya məhsulları',
        '39' => 'Plastik kütlələr və onlardan məmulatlar',
        '40' => 'Kauçuk, rezin və onlardan məmulatlar',
        '41' => 'Xam gön-dəri və emal olunmuş dəri',
        '42' => 'Dəri məmulatları; yəhər-qayış; səyahət ləvazimatı',
        '43' => 'Natural və süni xəz və onlardan məmulatlar',
        '44' => 'Ağac və ağacdan məmulatlar; ağac kömürü',
        '45' => 'Probka və ondan məmulatlar',
        '46' => 'Küləş və hörmə materiallarından məmulatlar',
        '47' => 'Ağacdan və ya lifli materialdan sellüloz',
        '48' => 'Kağız və karton; kağız kütləsindən məmulatlar',
        '49' => 'Çap kitabları, qəzetlər və çap məhsulları',
        '50' => 'İpək',
        '51' => 'Yun və heyvan tükü; at tükündən ip və parça',
        '52' => 'Pambıq',
        '53' => 'Digər bitki toxuculuq lifləri; kağız ipliyi',
        '54' => 'Kimyəvi saplar (filamentlər)',
        '55' => 'Kimyəvi ştapel lifləri',
        '56' => 'Pambıq yun, keçə, qeyri-toxunma materiallar; kanat',
        '57' => 'Xalçalar və toxuculuq döşəmə örtükləri',
        '58' => 'Xüsusi parçalar; tikmə; krujeva; qobelen',
        '59' => 'Hopdurulmuş və örtülmüş toxuculuq materialları',
        '60' => 'Trikotaj polotno',
        '61' => 'Trikotaj geyim və geyim ləvazimatı',
        '62' => 'Trikotaj olmayan geyim və geyim ləvazimatı',
        '63' => 'Digər hazır toxuculuq məmulatları; köhnə paltar',
        '64' => 'Ayaqqabılar və bənzər məmulatlar',
        '65' => 'Baş geyimləri və onların hissələri',
        '66' => 'Çətirlər, əl ağacları və qamçılar',
        '67' => 'Emal olunmuş lələk və tük; süni güllər',
        '68' => 'Daş, gips, sement, asbestdən məmulatlar',
        '69' => 'Keramika məmulatları',
        '70' => 'Şüşə və şüşədən məmulatlar',
        '71' => 'Mirvari, qiymətli daşlar və metallar; zərgərlik',
        '72' => 'Qara metallar (çuqun, dəmir, polad)',
        '73' => 'Qara metallardan məmulatlar',
        '74' => 'Mis və ondan məmulatlar',
        '75' => 'Nikel və ondan məmulatlar',
        '76' => 'Alüminium və ondan məmulatlar',
        '78' => 'Qurğuşun və ondan məmulatlar',
        '79' => 'Sink və ondan məmulatlar',
        '80' => 'Qalay və ondan məmulatlar',
        '81' => 'Digər adi metallar; metal-keramika',
        '82' => 'Alətlər, bıçaq məmulatları, çəngəl-qaşıq',
        '83' => 'Adi metallardan müxtəlif məmulatlar',
        '84' => 'Nüvə reaktorları, qazanlar, avadanlıq və mexaniki qurğular',
        '85' => 'Elektrik maşınları və avadanlığı',
        '86' => 'Dəmir yolu lokomotivləri, vaqonlar və avadanlıq',
        '87' => 'Yer nəqliyyatı vasitələri (dəmir yolundan başqa)',
        '88' => 'Uçuş və kosmik aparatları',
        '89' => 'Gəmilər, qayıqlar və üzən qurğular',
        '90' => 'Optik, foto, ölçü və tibbi cihazlar',
        '91' => 'Saatlar və onların hissələri',
        '92' => 'Musiqi alətləri və onların ləvazimatı',
        '93' => 'Silah və döyüş sursatı',
        '94' => 'Mebel; yataq ləvazimatı; işıqlandırma cihazları',
        '95' => 'Oyuncaqlar, oyunlar və idman ləvazimatı',
        '96' => 'Müxtəlif hazır məmulatlar',
        '97' => 'İncəsənət əsərləri və antikvariat',
        '99' => 'Xidmətlər',
    ];

    public static function title(string $chapter): ?string
    {
        return self::AZ[$chapter] ?? null;
    }
}
