<?php

namespace App\Support;

/**
 * Titles for the 4-digit XİF MN service positions (chapter 99) in az / en / ru.
 * Service names in the catalog are flat, so position titles can't be derived
 * from a breadcrumb — these are hand-authored from the real member items of each
 * position (a CPA/CPC-based service classification). Subposition (6-digit) titles
 * are derived from their own leaves by the rubricator builder; this map covers
 * the 64 positions, which are the first fork of the services branch.
 */
final class ServiceRubrics
{
    /** @var array<string, string> */
    public const POSITIONS = [
        '9901' => 'Kənd təsərrüfatı bitkiçilik xidmətləri',
        '9902' => 'Meşə təsərrüfatı xidmətləri',
        '9903' => 'Balıqçılıq və su bitkiçiliyinə yardımçı xidmətlər',
        '9909' => 'Dağ-mədən və neft-qaz hasilatına yardımçı xidmətlər',
        '9913' => 'Toxuculuq materiallarının rənglənməsi və emalı xidmətləri',
        '9918' => 'Çap xidmətləri və çap məhsulları',
        '9925' => 'Metalların emalı və örtülməsi xidmətləri',
        '9933' => 'Metal məmulatları və avadanlıqların təmiri və quraşdırılması',
        '9935' => 'Elektrik enerjisi və qaz təchizatı xidmətləri',
        '9936' => 'Su təchizatı və təmizlənməsi xidmətləri',
        '9937' => 'Kanalizasiya və tullantı sularının təmizlənməsi',
        '9938' => 'Tullantıların yığılması və emalı xidmətləri',
        '9939' => 'Ətraf mühitin bərpası və təmizləmə xidmətləri',
        '9941' => 'Binaların tikintisi (ümumtikinti) işləri',
        '9942' => 'Mülki tikinti işləri (yollar, qurğular)',
        '9943' => 'İxtisaslaşmış tikinti işləri',
        '9945' => 'Avtomobil ticarəti üzrə xidmətlər',
        '9946' => 'Topdansatış ticarəti xidmətləri',
        '9947' => 'Pərakəndə satış ticarəti xidmətləri',
        '9949' => 'Quru nəqliyyatı xidmətləri',
        '9950' => 'Su nəqliyyatı xidmətləri',
        '9951' => 'Hava nəqliyyatı xidmətləri',
        '9952' => 'Anbar və nəqliyyata yardımçı xidmətlər',
        '9953' => 'Poçt və kuryer xidmətləri',
        '9955' => 'Yerləşmə (qonaqlama) xidmətləri',
        '9956' => 'İaşə (yemək) xidmətləri',
        '9958' => 'Kitablar və nəşriyyat məhsulları',
        '9959' => 'Kino, video və media hazırlanması xidmətləri',
        '9960' => 'Radio və televiziya yayımı xidmətləri',
        '9961' => 'Telekommunikasiya xidmətləri',
        '9962' => 'İnformasiya texnologiyaları və proqram təminatı xidmətləri',
        '9963' => 'Verilənlərin emalı və veb-hostinq xidmətləri',
        '9964' => 'Kredit və depozit (bank) xidmətləri',
        '9965' => 'Sığorta və təkrarsığorta xidmətləri',
        '9966' => 'Maliyyə bazarlarına yardımçı və broker xidmətləri',
        '9968' => 'Daşınmaz əmlak üzrə xidmətlər',
        '9969' => 'Hüquq və hüquqi məsləhət xidmətləri',
        '9970' => 'İdarəetmə və konsaltinq xidmətləri',
        '9971' => 'Memarlıq və mühəndislik xidmətləri',
        '9972' => 'Elmi tədqiqat və işləmələr xidmətləri',
        '9973' => 'Reklam və marketinq xidmətləri',
        '9974' => 'Dizayn və foto xidmətləri',
        '9975' => 'Baytarlıq xidmətləri',
        '9977' => 'İcarə və lizinq xidmətləri',
        '9978' => 'İşədüzəltmə (məşğulluq) xidmətləri',
        '9979' => 'Səyahət agentliyi xidmətləri',
        '9980' => 'Təhlükəsizlik və mühafizə xidmətləri',
        '9981' => 'Binaların təmizlənməsi və abadlaşdırma xidmətləri',
        '9982' => 'İnzibati və ofis dəstəyi xidmətləri',
        '9984' => 'Dövlət idarəetməsi üzrə inzibati xidmətlər',
        '9985' => 'Təhsil xidmətləri',
        '9986' => 'Səhiyyə (tibbi) xidmətləri',
        '9987' => 'Yaşayış təminatlı sosial xidmətlər',
        '9988' => 'Yaşayış təminatsız sosial xidmətlər',
        '9990' => 'Səhnə sənəti və əyləncə xidmətləri',
        '9991' => 'Kitabxana, arxiv və muzey xidmətləri',
        '9992' => 'Qumar və mərc oyunları xidmətləri',
        '9993' => 'İdman və istirahət xidmətləri',
        '9994' => 'Üzvlük təşkilatlarının xidmətləri',
        '9995' => 'Ayaqqabı və şəxsi əşyaların təmiri',
        '9996' => 'Kimyəvi təmizləmə və boyama xidmətləri',
        '9997' => 'Ev təsərrüfatlarının muzdlu işçi xidmətləri',
        '9998' => 'Ev təsərrüfatlarının fərdi istehlak xidmətləri',
        '9999' => 'Ekstraterritorial təşkilatların xidmətləri',
    ];

    /** @var array<string, string> */
    public const POSITIONS_EN = [
        '9901' => 'Support services to crop production',
        '9902' => 'Forestry services',
        '9903' => 'Support services to fishing and aquaculture',
        '9909' => 'Support services to mining and oil & gas extraction',
        '9913' => 'Dyeing and finishing services for textiles',
        '9918' => 'Printing services and printed products',
        '9925' => 'Metal treatment and coating services',
        '9933' => 'Repair and installation of metal products and equipment',
        '9935' => 'Electricity and gas supply services',
        '9936' => 'Water supply and treatment services',
        '9937' => 'Sewerage and wastewater treatment services',
        '9938' => 'Waste collection and treatment services',
        '9939' => 'Remediation and environmental cleanup services',
        '9941' => 'Construction of buildings (general)',
        '9942' => 'Civil engineering works (roads, structures)',
        '9943' => 'Specialised construction works',
        '9945' => 'Motor vehicle trade services',
        '9946' => 'Wholesale trade services',
        '9947' => 'Retail trade services',
        '9949' => 'Land transport services',
        '9950' => 'Water transport services',
        '9951' => 'Air transport services',
        '9952' => 'Warehousing and transport support services',
        '9953' => 'Postal and courier services',
        '9955' => 'Accommodation services',
        '9956' => 'Food and beverage serving services',
        '9958' => 'Books and publishing products',
        '9959' => 'Motion picture, video and media production services',
        '9960' => 'Radio and television broadcasting services',
        '9961' => 'Telecommunications services',
        '9962' => 'Information technology and software services',
        '9963' => 'Data processing and web hosting services',
        '9964' => 'Credit and deposit (banking) services',
        '9965' => 'Insurance and reinsurance services',
        '9966' => 'Financial market support and brokerage services',
        '9968' => 'Real estate services',
        '9969' => 'Legal and legal advisory services',
        '9970' => 'Management and consulting services',
        '9971' => 'Architectural and engineering services',
        '9972' => 'Scientific research and development services',
        '9973' => 'Advertising and marketing services',
        '9974' => 'Design and photography services',
        '9975' => 'Veterinary services',
        '9977' => 'Rental and leasing services',
        '9978' => 'Employment (staffing) services',
        '9979' => 'Travel agency services',
        '9980' => 'Security and protection services',
        '9981' => 'Building cleaning and landscaping services',
        '9982' => 'Administrative and office support services',
        '9984' => 'Public administration services',
        '9985' => 'Education services',
        '9986' => 'Human health (medical) services',
        '9987' => 'Residential care services',
        '9988' => 'Social work services without accommodation',
        '9990' => 'Performing arts and entertainment services',
        '9991' => 'Library, archive and museum services',
        '9992' => 'Gambling and betting services',
        '9993' => 'Sports and recreation services',
        '9994' => 'Services of membership organisations',
        '9995' => 'Repair of footwear and personal goods',
        '9996' => 'Dry-cleaning and dyeing services',
        '9997' => 'Services of households as employers of staff',
        '9998' => 'Goods and services produced by households for own use',
        '9999' => 'Services of extraterritorial organisations',
    ];

    /** @var array<string, string> */
    public const POSITIONS_RU = [
        '9901' => 'Услуги в растениеводстве',
        '9902' => 'Услуги лесного хозяйства',
        '9903' => 'Вспомогательные услуги в рыболовстве и аквакультуре',
        '9909' => 'Вспомогательные услуги в горнодобыче и добыче нефти и газа',
        '9913' => 'Услуги окраски и отделки текстильных материалов',
        '9918' => 'Полиграфические услуги и печатная продукция',
        '9925' => 'Услуги обработки и покрытия металлов',
        '9933' => 'Ремонт и монтаж металлоизделий и оборудования',
        '9935' => 'Услуги электро- и газоснабжения',
        '9936' => 'Услуги водоснабжения и водоподготовки',
        '9937' => 'Канализация и очистка сточных вод',
        '9938' => 'Услуги сбора и переработки отходов',
        '9939' => 'Услуги рекультивации и очистки окружающей среды',
        '9941' => 'Строительство зданий (общестроительные работы)',
        '9942' => 'Работы по гражданскому строительству (дороги, сооружения)',
        '9943' => 'Специализированные строительные работы',
        '9945' => 'Услуги торговли автотранспортными средствами',
        '9946' => 'Услуги оптовой торговли',
        '9947' => 'Услуги розничной торговли',
        '9949' => 'Услуги сухопутного транспорта',
        '9950' => 'Услуги водного транспорта',
        '9951' => 'Услуги воздушного транспорта',
        '9952' => 'Складские и вспомогательные транспортные услуги',
        '9953' => 'Почтовые и курьерские услуги',
        '9955' => 'Услуги по временному проживанию',
        '9956' => 'Услуги общественного питания',
        '9958' => 'Книги и издательская продукция',
        '9959' => 'Услуги производства кино, видео и медиа',
        '9960' => 'Услуги радио- и телевещания',
        '9961' => 'Телекоммуникационные услуги',
        '9962' => 'Услуги в сфере ИТ и программного обеспечения',
        '9963' => 'Услуги обработки данных и веб-хостинга',
        '9964' => 'Кредитные и депозитные (банковские) услуги',
        '9965' => 'Услуги страхования и перестрахования',
        '9966' => 'Вспомогательные и брокерские услуги на финансовых рынках',
        '9968' => 'Услуги в сфере недвижимости',
        '9969' => 'Юридические и консультационные услуги',
        '9970' => 'Услуги управления и консалтинга',
        '9971' => 'Архитектурные и инженерные услуги',
        '9972' => 'Услуги научных исследований и разработок',
        '9973' => 'Рекламные и маркетинговые услуги',
        '9974' => 'Услуги дизайна и фотографии',
        '9975' => 'Ветеринарные услуги',
        '9977' => 'Услуги аренды и лизинга',
        '9978' => 'Услуги по трудоустройству (подбор персонала)',
        '9979' => 'Услуги турагентств',
        '9980' => 'Услуги безопасности и охраны',
        '9981' => 'Услуги уборки зданий и благоустройства',
        '9982' => 'Административные и офисные вспомогательные услуги',
        '9984' => 'Административные услуги государственного управления',
        '9985' => 'Услуги в сфере образования',
        '9986' => 'Медицинские услуги (здравоохранение)',
        '9987' => 'Социальные услуги с проживанием',
        '9988' => 'Социальные услуги без проживания',
        '9990' => 'Услуги в сфере исполнительского искусства и развлечений',
        '9991' => 'Услуги библиотек, архивов и музеев',
        '9992' => 'Услуги азартных игр и заключения пари',
        '9993' => 'Услуги спорта и отдыха',
        '9994' => 'Услуги организаций на основе членства',
        '9995' => 'Ремонт обуви и личных вещей',
        '9996' => 'Услуги химчистки и окраски',
        '9997' => 'Услуги домашних хозяйств по найму работников',
        '9998' => 'Услуги домашних хозяйств для собственного потребления',
        '9999' => 'Услуги экстерриториальных организаций',
    ];

    public static function title(string $position, string $lang = 'az'): ?string
    {
        return match ($lang) {
            'en' => self::POSITIONS_EN[$position] ?? null,
            'ru' => self::POSITIONS_RU[$position] ?? null,
            default => self::POSITIONS[$position] ?? null,
        };
    }
}
